export const DrawCardConstants = {
    DRAWCARD_REQUEST: 'DRAWCARD_REQUEST',
    DRAWCARD_SUCCESS: 'DRAWCARD_SUCCESS',
    DRAWCARD_FAILURE: 'DRAWCARD_FAILURE',
    DRAWCARD_TURN_TO_MAINPAGE: 'DRAWCARD_TURN_TO_MAINPAGE',

    GET_PERSONAL_DATA_REQUEST: 'GET_PERSONAL_DATA_REQUEST',
    GET_PERSONAL_DATA_SUCCESS: 'GET_PERSONAL_DATA_SUCCESS',
    GET_PERSONAL_DATA_FAILURE: 'GET_PERSONAL_DATA_FAILURE',
}