export const LogRegConstants = {
    /*REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',*/

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_INVALIDPASSWORD: 'LOGIN_INVALIDPASSWORD',
    LOGIN_UNAUTHORIZED: 'LOGIN_UNAUTHORIZED',

    LOGOUT: 'LOGOUT',

}