export const LogRegConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    REGISTER_ACCOUNT_EXIST: 'REGISTER_ACCOUNT_EXIST',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_INVALIDPASSWORD: 'LOGIN_INVALIDPASSWORD',
    LOGIN_UNAUTHORIZED: 'LOGIN_UNAUTHORIZED',
    LOGIN_TO_LOGIN_PAGE: 'LOGIN_TO_LOGIN_PAGE',

    LOGOUT: 'LOGOUT',

}